name: ColoredNames
main: me.foncused.colorednames.ColoredNames
version: 1.6.8
author: foncused

permissions:
  colorednames.all:
    default: false
    children:
      colorednames.black: true
      colorednames.dark_blue: true
      colorednames.dark_green: true
      colorednames.dark_aqua: true
      colorednames.dark_red: true
      colorednames.dark_purple: true
      colorednames.gold: true
      colorednames.gray: true
      colorednames.dark_gray: true
      colorednames.blue: true
      colorednames.green: true
      colorednames.aqua: true
      colorednames.red: true
      colorednames.light_purple: true
      colorednames.yellow: true
      colorednames.white: true
      colorednames.obfuscated: true
      colorednames.bold: true
      colorednames.strikethrough: true
      colorednames.underline: true
      colorednames.italic: true
  colorednames.black:
    default: false
  colorednames.dark_blue:
    default: false
  colorednames.dark_green:
    default: false
  colorednames.dark_aqua:
    default: false
  colorednames.dark_red:
    default: false
  colorednames.dark_purple:
    default: false
  colorednames.gold:
    default: false
  colorednames.gray:
    default: false
  colorednames.dark_gray:
    default: false
  colorednames.blue:
    default: false
  colorednames.green:
    default: false
  colorednames.aqua:
    default: false
  colorednames.red:
    default: false
  colorednames.light_purple:
    default: false
  colorednames.yellow:
    default: false
  colorednames.white:
    default: false
  colorednames.obfuscated:
    default: false
  colorednames.bold:
    default: false
  colorednames.strikethrough:
    default: false
  colorednames.underline:
    default: false
  colorednames.italic:
    default: false
